language: android
sudo: required
jdk: oraclejdk8

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

env:
  - ANDROID_API_LEVEL = 25
  - ANDROID_BUILD_TOOLS =26.0.3

android:
  component:
    - tools
    - platform-tools
    - build-tools-26.0.3
    - android-25
    - extra-google-m2repository
    - extra-android-m2repository # for design library
    - addon-google_apis-google-19 # google play services

install:
  - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2"
  - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2"

before_script:
    - sudo apt-get install jq
    - echo building

script: 
    - ./gradlew -version
    - "./gradlew assembleDebug"

notifications:
  email:
    - s124202468@gmail.com